baseURL = "https://jeqo.github.io/peru-congreso"
title = "Congreso Per√∫"
theme = "book"

languageCode = "es-pe"
DefaultContentLanguage = "es"

googleAnalytics = "UA-49047812-5"

Paginate = 25

[taxonomies]
  estado = "estados"
  proponente = "proponentes"
  grupo = "grupos"
  autor = "autores"
  sector = "sectores"
  periodo = "periodos"
  legislatura = "legislaturas"

[params]
  BookMenuBundle = "/menu"
  BookRepo = 'https://github.com/jeqo/peru-congreso'